### ISSUE TITLE
UriAction isn't working

### ISSUE THREAD

**Issue by davidwengier** [aliencube/microsoft-teams-actions#1]
I think because you're just deserializing the JSON as `BaseAction`, which has no extra properties, the `targets` I'm specifying for me UriAction are being stripped.

See my input JSON:
```
[ { "@type": "OpenUri", "name": "View in GitHub", "targets": [ { "os": "default", "uri": "https://github.com/dotnet/project-system/pull/5812" } ] } ]
```

And the resulting data sent to the webhook:
```
"potentialAction": [
    {
      "@type": "OpenUri",
      "name": "View in GitHub"
    }
  ]
```

Full logs of the run are here: https://github.com/dotnet/project-system/pull/5812/checks?check_run_id=399958891

Is there a way to get links into the message otherwise?

**Comment by justinyoo** [comment]
@davidwengier Thanks for raising the issue! I'll have a look. The deserialising logic should be smarter than the current.

**Comment by davidwengier** [comment]
I'll try to find some time to have a look too. I got links working fine via markdown in the end though :)
