### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by HarishBaskarTR** [aliencube/microsoft-teams-actions#10]
This action only works on linux. Is there a way to make this work on Windows too?
Also, there is no mention about this in Readme section

**Comment by justinyoo** [comment]
@HarishBaskarTR No, unfortunately. It's based on Docker Action which currently supports Linux based.

**Comment by tyson-benson** [comment]
Would have been helpful to mention it wasn't supported on Windows in the readme.
